// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: amoled_display

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_welcomeScreen
void ui_welcomeScreen_screen_init(void);
lv_obj_t *ui_welcomeScreen;
lv_obj_t *ui_welcomeLabel;
// CUSTOM VARIABLES


// SCREEN: ui_NoConnectionScreen
void ui_NoConnectionScreen_screen_init(void);
lv_obj_t *ui_NoConnectionScreen;
lv_obj_t *ui_NoWifiImage;
lv_obj_t *ui_BatMediumImage;
lv_obj_t *ui_CrossImage;
lv_obj_t *ui_NoWifiLabel;
void ui_event_WifiSetupBtn( lv_event_t * e);
lv_obj_t *ui_WifiSetupBtn;
lv_obj_t *ui_WifiSetupLabel;
// CUSTOM VARIABLES


// SCREEN: ui_setupWifiScreen
void ui_setupWifiScreen_screen_init(void);
lv_obj_t *ui_setupWifiScreen;
lv_obj_t *ui_NoWifiImage1;
lv_obj_t *ui_BatMediumImage1;
lv_obj_t *ui_NoWifiLabel1;
lv_obj_t *ui_Spinner1;
lv_obj_t *ui_SSIDLabel;
lv_obj_t *ui_URLLabel;
// CUSTOM VARIABLES


// SCREEN: ui_mainScreen
void ui_mainScreen_screen_init(void);
lv_obj_t *ui_mainScreen;
lv_obj_t *ui_WifiImage;
lv_obj_t *ui_BatMediumImage2;
void ui_event_powerButton( lv_event_t * e);
lv_obj_t *ui_powerButton;
lv_obj_t *ui_steamButton;
lv_obj_t *ui_timeLabel;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t *ui_imgset_logo_[1] = {&ui_img_logo_2_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_WifiSetupBtn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      wifiSetup( e );
}
}

void ui_event_powerButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      turnOnMachine( e );
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_welcomeScreen_screen_init();
ui_NoConnectionScreen_screen_init();
ui_setupWifiScreen_screen_init();
ui_mainScreen_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_welcomeScreen);
}
