// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: amoled_display

#ifndef _AMOLED_DISPLAY_UI_H
#define _AMOLED_DISPLAY_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_welcomeScreen
void ui_welcomeScreen_screen_init(void);
extern lv_obj_t *ui_welcomeScreen;
extern lv_obj_t *ui_welcomeLabel;
// CUSTOM VARIABLES

// SCREEN: ui_NoConnectionScreen
void ui_NoConnectionScreen_screen_init(void);
extern lv_obj_t *ui_NoConnectionScreen;
extern lv_obj_t *ui_NoWifiImage;
extern lv_obj_t *ui_BatMediumImage;
extern lv_obj_t *ui_CrossImage;
extern lv_obj_t *ui_NoWifiLabel;
void ui_event_WifiSetupBtn( lv_event_t * e);
extern lv_obj_t *ui_WifiSetupBtn;
extern lv_obj_t *ui_WifiSetupLabel;
// CUSTOM VARIABLES

// SCREEN: ui_setupWifiScreen
void ui_setupWifiScreen_screen_init(void);
extern lv_obj_t *ui_setupWifiScreen;
extern lv_obj_t *ui_NoWifiImage1;
extern lv_obj_t *ui_BatMediumImage1;
extern lv_obj_t *ui_NoWifiLabel1;
extern lv_obj_t *ui_Spinner1;
extern lv_obj_t *ui_SSIDLabel;
extern lv_obj_t *ui_URLLabel;
// CUSTOM VARIABLES

// SCREEN: ui_mainScreen
void ui_mainScreen_screen_init(void);
extern lv_obj_t *ui_mainScreen;
extern lv_obj_t *ui_WifiImage;
extern lv_obj_t *ui_BatMediumImage2;
extern lv_obj_t *ui_powerButton;
extern lv_obj_t *ui_steamButton;
extern lv_obj_t *ui_timeLabel;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_262687307);   // assets/Wifi Slash Icon (2).png
LV_IMG_DECLARE( ui_img_battery_medium_icon_png);   // assets/Battery Medium Icon.png
LV_IMG_DECLARE( ui_img_x_circle_icon_png);   // assets/X Circle Icon.png
LV_IMG_DECLARE( ui_img_1794397354);   // assets/WiFi Icon (2).png
LV_IMG_DECLARE( ui_img_power_png);   // assets/power.png
LV_IMG_DECLARE( ui_img_steam_png);   // assets/steam.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
