// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: amoled_display

#ifndef _AMOLED_DISPLAY_UI_H
#define _AMOLED_DISPLAY_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_welcomeScreen
void ui_welcomeScreen_screen_init(void);
extern lv_obj_t *ui_welcomeScreen;
extern lv_obj_t *ui_welcomeLabel;
// CUSTOM VARIABLES

// SCREEN: ui_NoConnectionScreen
void ui_NoConnectionScreen_screen_init(void);
extern lv_obj_t *ui_NoConnectionScreen;
extern lv_obj_t *ui_NoWifiImage;
extern lv_obj_t *ui_CrossImage;
extern lv_obj_t *ui_ErrorLabel;
void ui_event_WifiSetupBtn( lv_event_t * e);
extern lv_obj_t *ui_WifiSetupBtn;
extern lv_obj_t *ui_WifiSetupLabel;
extern lv_obj_t *ui_BatImage;
// CUSTOM VARIABLES

// SCREEN: ui_setupWifiScreen
void ui_setupWifiScreen_screen_init(void);
extern lv_obj_t *ui_setupWifiScreen;
extern lv_obj_t *ui_NoWifiImage1;
extern lv_obj_t *ui_BatImage1;
extern lv_obj_t *ui_NoWifiLabel1;
extern lv_obj_t *ui_Spinner1;
extern lv_obj_t *ui_SSIDLabel;
extern lv_obj_t *ui_URLLabel;
// CUSTOM VARIABLES

// SCREEN: ui_mainScreen
void ui_mainScreen_screen_init(void);
extern lv_obj_t *ui_mainScreen;
extern lv_obj_t *ui_WifiImage;
extern lv_obj_t *ui_BatImage2;
void ui_event_powerButton( lv_event_t * e);
extern lv_obj_t *ui_powerButton;
extern lv_obj_t *ui_steamButton;
extern lv_obj_t *ui_timeLabel;
extern lv_obj_t *ui_Arc2;
extern lv_obj_t *ui_Arc3;
extern lv_obj_t *ui_CoffeeImage;
extern lv_obj_t *ui_SteamImage;
extern lv_obj_t *ui_CoffeeLabel;
extern lv_obj_t *ui_SteamLabel;
extern lv_obj_t *ui_CoffeeTempLabel;
extern lv_obj_t *ui_BoilerTempLabel;
extern lv_obj_t *ui_waterImage;
extern lv_obj_t *ui_waterAlarmLabel;
extern lv_obj_t *ui_SecPanel;
extern lv_obj_t *ui_SecValueLabel;
extern lv_obj_t *ui_SecondsLabel;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_wifi0_png);   // assets/wifi0.png
LV_IMG_DECLARE( ui_img_cross_png);   // assets/cross.png
LV_IMG_DECLARE( ui_img_battery1_png);   // assets/battery1.png
LV_IMG_DECLARE( ui_img_battery0_png);   // assets/battery0.png
LV_IMG_DECLARE( ui_img_power_png);   // assets/power.png
LV_IMG_DECLARE( ui_img_steam_png);   // assets/steam.png
LV_IMG_DECLARE( ui_img_coffee_png);   // assets/coffee.png
LV_IMG_DECLARE( ui_img_wind_png);   // assets/wind.png
LV_IMG_DECLARE( ui_img_drop_2_png);   // assets/drop_2.png
LV_IMG_DECLARE( ui_img_battery2_png);   // assets/battery2.png
LV_IMG_DECLARE( ui_img_battery3_png);   // assets/battery3.png
LV_IMG_DECLARE( ui_img_wifi1_png);   // assets/wifi1.png
LV_IMG_DECLARE( ui_img_wifi2_png);   // assets/wifi2.png
LV_IMG_DECLARE( ui_img_wifi3_png);   // assets/wifi3.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
