// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: amoled_display

#include "ui.h"

void ui_mainScreen_screen_init(void)
{
ui_mainScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_mainScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_mainScreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_mainScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_WifiImage = lv_img_create(ui_mainScreen);
lv_img_set_src(ui_WifiImage, &ui_img_1794397354);
lv_obj_set_width( ui_WifiImage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_WifiImage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_WifiImage, 156 );
lv_obj_set_y( ui_WifiImage, -93 );
lv_obj_set_align( ui_WifiImage, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_WifiImage, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_WifiImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_BatMediumImage2 = lv_img_create(ui_mainScreen);
lv_img_set_src(ui_BatMediumImage2, &ui_img_battery_medium_icon_png);
lv_obj_set_width( ui_BatMediumImage2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BatMediumImage2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BatMediumImage2, 215 );
lv_obj_set_y( ui_BatMediumImage2, -92 );
lv_obj_set_align( ui_BatMediumImage2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BatMediumImage2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_BatMediumImage2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_powerButton = lv_btn_create(ui_mainScreen);
lv_obj_set_width( ui_powerButton, 78);
lv_obj_set_height( ui_powerButton, 70);
lv_obj_set_x( ui_powerButton, 213 );
lv_obj_set_y( ui_powerButton, -22 );
lv_obj_set_align( ui_powerButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_powerButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_powerButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_powerButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_powerButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_powerButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_img_src( ui_powerButton, &ui_img_power_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_powerButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_powerButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_steamButton = lv_btn_create(ui_mainScreen);
lv_obj_set_width( ui_steamButton, 74);
lv_obj_set_height( ui_steamButton, 74);
lv_obj_set_x( ui_steamButton, 213 );
lv_obj_set_y( ui_steamButton, 58 );
lv_obj_set_align( ui_steamButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_steamButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_steamButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_steamButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_steamButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_steamButton, &ui_img_steam_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_steamButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_steamButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_timeLabel = lv_label_create(ui_mainScreen);
lv_obj_set_width( ui_timeLabel, 84);
lv_obj_set_height( ui_timeLabel, 27);
lv_obj_set_x( ui_timeLabel, -214 );
lv_obj_set_y( ui_timeLabel, -94 );
lv_obj_set_align( ui_timeLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_timeLabel,"");
lv_obj_set_style_text_font(ui_timeLabel, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);


}
