// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: amoled_display

#include "ui.h"

void ui_mainScreen_screen_init(void)
{
ui_mainScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_mainScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_mainScreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_mainScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_WifiImage = lv_img_create(ui_mainScreen);
lv_img_set_src(ui_WifiImage, &ui_img_wifi0_png);
lv_obj_set_width( ui_WifiImage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_WifiImage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_WifiImage, 156 );
lv_obj_set_y( ui_WifiImage, -94 );
lv_obj_set_align( ui_WifiImage, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_WifiImage, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_WifiImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_BatImage2 = lv_img_create(ui_mainScreen);
lv_img_set_src(ui_BatImage2, &ui_img_battery0_png);
lv_obj_set_width( ui_BatImage2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BatImage2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BatImage2, 215 );
lv_obj_set_y( ui_BatImage2, -92 );
lv_obj_set_align( ui_BatImage2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BatImage2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_BatImage2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_powerButton = lv_btn_create(ui_mainScreen);
lv_obj_set_width( ui_powerButton, 78);
lv_obj_set_height( ui_powerButton, 70);
lv_obj_set_x( ui_powerButton, 213 );
lv_obj_set_y( ui_powerButton, -22 );
lv_obj_set_align( ui_powerButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_powerButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_powerButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_powerButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_powerButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_powerButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_img_src( ui_powerButton, &ui_img_power_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_powerButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_powerButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_steamButton = lv_btn_create(ui_mainScreen);
lv_obj_set_width( ui_steamButton, 74);
lv_obj_set_height( ui_steamButton, 74);
lv_obj_set_x( ui_steamButton, 213 );
lv_obj_set_y( ui_steamButton, 58 );
lv_obj_set_align( ui_steamButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_steamButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_steamButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_steamButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_steamButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_steamButton, &ui_img_steam_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_steamButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_steamButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_timeLabel = lv_label_create(ui_mainScreen);
lv_obj_set_width( ui_timeLabel, 92);
lv_obj_set_height( ui_timeLabel, 27);
lv_obj_set_x( ui_timeLabel, -208 );
lv_obj_set_y( ui_timeLabel, -95 );
lv_obj_set_align( ui_timeLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_timeLabel,"");
lv_obj_set_style_text_font(ui_timeLabel, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CoffeeCountIcon = lv_img_create(ui_mainScreen);
lv_img_set_src(ui_CoffeeCountIcon, &ui_img_coffee_png);
lv_obj_set_width( ui_CoffeeCountIcon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CoffeeCountIcon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_CoffeeCountIcon, -110 );
lv_obj_set_y( ui_CoffeeCountIcon, -94 );
lv_obj_set_align( ui_CoffeeCountIcon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_CoffeeCountIcon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_CoffeeCountIcon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_CoffeeCountLabel = lv_label_create(ui_mainScreen);
lv_obj_set_width( ui_CoffeeCountLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CoffeeCountLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_CoffeeCountLabel, -70 );
lv_obj_set_y( ui_CoffeeCountLabel, -95 );
lv_obj_set_align( ui_CoffeeCountLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_CoffeeCountLabel,"0");
lv_obj_set_style_text_font(ui_CoffeeCountLabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FlushCountIcon = lv_img_create(ui_mainScreen);
lv_img_set_src(ui_FlushCountIcon, &ui_img_drop_2_png);
lv_img_set_zoom(ui_FlushCountIcon, 128);
lv_obj_set_width( ui_FlushCountIcon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_FlushCountIcon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_FlushCountIcon, -30 );
lv_obj_set_y( ui_FlushCountIcon, -94 );
lv_obj_set_align( ui_FlushCountIcon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_FlushCountIcon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_FlushCountIcon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_FlushCountLabel = lv_label_create(ui_mainScreen);
lv_obj_set_width( ui_FlushCountLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_FlushCountLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_FlushCountLabel, 10 );
lv_obj_set_y( ui_FlushCountLabel, -95 );
lv_obj_set_align( ui_FlushCountLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_FlushCountLabel,"0");
lv_obj_set_style_text_font(ui_FlushCountLabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Arc2 = lv_arc_create(ui_mainScreen);
lv_obj_set_width( ui_Arc2, 150);
lv_obj_set_height( ui_Arc2, 150);
lv_obj_set_x( ui_Arc2, -163 );
lv_obj_set_y( ui_Arc2, 5 );
lv_obj_set_align( ui_Arc2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Arc2, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_arc_set_value(ui_Arc2, 0);
lv_obj_set_style_arc_rounded(ui_Arc2, false, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_Arc2, lv_color_hex(0x4040FF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Arc2, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_Arc2, 10, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Arc2, lv_color_hex(0x4040FF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Arc2, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Arc3 = lv_arc_create(ui_mainScreen);
lv_obj_set_width( ui_Arc3, 150);
lv_obj_set_height( ui_Arc3, 150);
lv_obj_set_x( ui_Arc3, 32 );
lv_obj_set_y( ui_Arc3, 0 );
lv_obj_set_align( ui_Arc3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Arc3, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_arc_set_value(ui_Arc3, 0);

lv_obj_set_style_arc_color(ui_Arc3, lv_color_hex(0x4040FF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Arc3, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_Arc3, 10, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Arc3, lv_color_hex(0x4040FF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Arc3, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_CoffeeImage = lv_img_create(ui_mainScreen);
lv_img_set_src(ui_CoffeeImage, &ui_img_coffee_png);
lv_obj_set_width( ui_CoffeeImage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CoffeeImage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_CoffeeImage, -162 );
lv_obj_set_y( ui_CoffeeImage, 59 );
lv_obj_set_align( ui_CoffeeImage, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_CoffeeImage, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_CoffeeImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SteamImage = lv_img_create(ui_mainScreen);
lv_img_set_src(ui_SteamImage, &ui_img_wind_png);
lv_obj_set_width( ui_SteamImage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SteamImage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SteamImage, 35 );
lv_obj_set_y( ui_SteamImage, 55 );
lv_obj_set_align( ui_SteamImage, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SteamImage, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_SteamImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_CoffeeLabel = lv_label_create(ui_mainScreen);
lv_obj_set_width( ui_CoffeeLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CoffeeLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_CoffeeLabel, -164 );
lv_obj_set_y( ui_CoffeeLabel, -1 );
lv_obj_set_align( ui_CoffeeLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_CoffeeLabel,"OFF");
lv_obj_set_style_text_font(ui_CoffeeLabel, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SteamLabel = lv_label_create(ui_mainScreen);
lv_obj_set_width( ui_SteamLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SteamLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SteamLabel, 31 );
lv_obj_set_y( ui_SteamLabel, -2 );
lv_obj_set_align( ui_SteamLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_SteamLabel,"OFF");
lv_obj_set_style_text_font(ui_SteamLabel, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CoffeeTempLabel = lv_label_create(ui_mainScreen);
lv_obj_set_width( ui_CoffeeTempLabel, 42);
lv_obj_set_height( ui_CoffeeTempLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_CoffeeTempLabel, -159 );
lv_obj_set_y( ui_CoffeeTempLabel, 88 );
lv_obj_set_align( ui_CoffeeTempLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_CoffeeTempLabel,"");
lv_obj_set_style_text_align(ui_CoffeeTempLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BoilerTempLabel = lv_label_create(ui_mainScreen);
lv_obj_set_width( ui_BoilerTempLabel, lv_pct(8));
lv_obj_set_height( ui_BoilerTempLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BoilerTempLabel, 34 );
lv_obj_set_y( ui_BoilerTempLabel, 83 );
lv_obj_set_align( ui_BoilerTempLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_BoilerTempLabel,"");
lv_obj_set_style_text_align(ui_BoilerTempLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_waterImage = lv_img_create(ui_mainScreen);
lv_img_set_src(ui_waterImage, &ui_img_drop_2_png);
lv_obj_set_width( ui_waterImage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_waterImage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_waterImage, -47 );
lv_obj_set_y( ui_waterImage, 5 );
lv_obj_set_align( ui_waterImage, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_waterImage, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_waterImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_waterAlarmLabel = lv_label_create(ui_mainScreen);
lv_obj_set_width( ui_waterAlarmLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_waterAlarmLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_waterAlarmLabel, -48 );
lv_obj_set_y( ui_waterAlarmLabel, 63 );
lv_obj_set_align( ui_waterAlarmLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_waterAlarmLabel,"Refill Water");
lv_obj_add_flag( ui_waterAlarmLabel, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_style_text_font(ui_waterAlarmLabel, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SecPanel = lv_obj_create(ui_mainScreen);
lv_obj_set_width( ui_SecPanel, 150);
lv_obj_set_height( ui_SecPanel, 150);
lv_obj_set_x( ui_SecPanel, -89 );
lv_obj_set_y( ui_SecPanel, -3 );
lv_obj_set_align( ui_SecPanel, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SecPanel, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_SecPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_SecPanel, 75, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_SecPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_SecPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SecValueLabel = lv_label_create(ui_SecPanel);
lv_obj_set_width( ui_SecValueLabel, 116);
lv_obj_set_height( ui_SecValueLabel, lv_pct(43));
lv_obj_set_x( ui_SecValueLabel, 1 );
lv_obj_set_y( ui_SecValueLabel, 1 );
lv_obj_set_align( ui_SecValueLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_SecValueLabel,"");
lv_obj_add_flag( ui_SecValueLabel, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_style_text_color(ui_SecValueLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SecValueLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_SecValueLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SecValueLabel, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SecondsLabel = lv_label_create(ui_mainScreen);
lv_obj_set_width( ui_SecondsLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SecondsLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SecondsLabel, 111 );
lv_obj_set_y( ui_SecondsLabel, -4 );
lv_obj_set_align( ui_SecondsLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_SecondsLabel,"Seconds");
lv_obj_add_flag( ui_SecondsLabel, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_style_text_font(ui_SecondsLabel, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_powerButton, ui_event_powerButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_steamButton, ui_event_steamButton, LV_EVENT_ALL, NULL);

}
