// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: amoled_display

#include "ui.h"

void ui_NoConnectionScreen_screen_init(void)
{
ui_NoConnectionScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_NoConnectionScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_NoWifiImage = lv_img_create(ui_NoConnectionScreen);
lv_img_set_src(ui_NoWifiImage, &ui_img_nowifi_png);
lv_obj_set_width( ui_NoWifiImage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_NoWifiImage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_NoWifiImage, 156 );
lv_obj_set_y( ui_NoWifiImage, -93 );
lv_obj_set_align( ui_NoWifiImage, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_NoWifiImage, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_NoWifiImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_BatMediumImage = lv_img_create(ui_NoConnectionScreen);
lv_img_set_src(ui_BatMediumImage, &ui_img_batterymedium_png);
lv_obj_set_width( ui_BatMediumImage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BatMediumImage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BatMediumImage, 215 );
lv_obj_set_y( ui_BatMediumImage, -92 );
lv_obj_set_align( ui_BatMediumImage, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BatMediumImage, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_BatMediumImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_CrossImage = lv_img_create(ui_NoConnectionScreen);
lv_img_set_src(ui_CrossImage, &ui_img_cross_png);
lv_obj_set_width( ui_CrossImage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CrossImage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_CrossImage, -195 );
lv_obj_set_y( ui_CrossImage, -10 );
lv_obj_set_align( ui_CrossImage, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_CrossImage, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_CrossImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_NoWifiLabel = lv_label_create(ui_NoConnectionScreen);
lv_obj_set_width( ui_NoWifiLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_NoWifiLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_NoWifiLabel, 0 );
lv_obj_set_y( ui_NoWifiLabel, -12 );
lv_obj_set_align( ui_NoWifiLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_NoWifiLabel,"No WiFi Connection \nPlease restart Wifi Setup");
lv_obj_set_style_text_font(ui_NoWifiLabel, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_WifiSetupBtn = lv_btn_create(ui_NoConnectionScreen);
lv_obj_set_width( ui_WifiSetupBtn, 151);
lv_obj_set_height( ui_WifiSetupBtn, 53);
lv_obj_set_x( ui_WifiSetupBtn, 0 );
lv_obj_set_y( ui_WifiSetupBtn, 63 );
lv_obj_set_align( ui_WifiSetupBtn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_WifiSetupBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_WifiSetupBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_WifiSetupBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_WifiSetupBtn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_WifiSetupBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_WifiSetupBtn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_WifiSetupBtn, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_WifiSetupBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_WifiSetupBtn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_WifiSetupLabel = lv_label_create(ui_WifiSetupBtn);
lv_obj_set_width( ui_WifiSetupLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_WifiSetupLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_WifiSetupLabel, -1 );
lv_obj_set_y( ui_WifiSetupLabel, 0 );
lv_obj_set_align( ui_WifiSetupLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_WifiSetupLabel,"Start WiFi Setup");
lv_obj_set_style_text_color(ui_WifiSetupLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_WifiSetupLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_WifiSetupLabel, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_WifiSetupBtn, ui_event_WifiSetupBtn, LV_EVENT_ALL, NULL);

}
