// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: amoled_display

#include "ui.h"

void ui_setupWifiScreen_screen_init(void)
{
ui_setupWifiScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_setupWifiScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_NoWifiImage1 = lv_img_create(ui_setupWifiScreen);
lv_img_set_src(ui_NoWifiImage1, &ui_img_nowifi_png);
lv_obj_set_width( ui_NoWifiImage1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_NoWifiImage1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_NoWifiImage1, 156 );
lv_obj_set_y( ui_NoWifiImage1, -93 );
lv_obj_set_align( ui_NoWifiImage1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_NoWifiImage1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_NoWifiImage1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_BatMediumImage1 = lv_img_create(ui_setupWifiScreen);
lv_img_set_src(ui_BatMediumImage1, &ui_img_batterymedium_png);
lv_obj_set_width( ui_BatMediumImage1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BatMediumImage1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BatMediumImage1, 215 );
lv_obj_set_y( ui_BatMediumImage1, -92 );
lv_obj_set_align( ui_BatMediumImage1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BatMediumImage1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_BatMediumImage1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_NoWifiLabel1 = lv_label_create(ui_setupWifiScreen);
lv_obj_set_width( ui_NoWifiLabel1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_NoWifiLabel1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_NoWifiLabel1, 29 );
lv_obj_set_y( ui_NoWifiLabel1, -16 );
lv_obj_set_align( ui_NoWifiLabel1, LV_ALIGN_CENTER );
lv_label_set_text(ui_NoWifiLabel1,"Please connect to Wifi \nsetup the device via browser");
lv_obj_set_style_text_font(ui_NoWifiLabel1, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Spinner1 = lv_spinner_create(ui_setupWifiScreen,1000,90);
lv_obj_set_width( ui_Spinner1, 87);
lv_obj_set_height( ui_Spinner1, 82);
lv_obj_set_x( ui_Spinner1, -193 );
lv_obj_set_y( ui_Spinner1, -12 );
lv_obj_set_align( ui_Spinner1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Spinner1, LV_OBJ_FLAG_CLICKABLE );    /// Flags

lv_obj_set_style_arc_color(ui_Spinner1, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Spinner1, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_SSIDLabel = lv_label_create(ui_setupWifiScreen);
lv_obj_set_width( ui_SSIDLabel, lv_pct(38));
lv_obj_set_height( ui_SSIDLabel, lv_pct(10));
lv_obj_set_x( ui_SSIDLabel, -24 );
lv_obj_set_y( ui_SSIDLabel, 36 );
lv_obj_set_align( ui_SSIDLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_SSIDLabel,"");
lv_obj_set_style_text_font(ui_SSIDLabel, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_URLLabel = lv_label_create(ui_setupWifiScreen);
lv_obj_set_width( ui_URLLabel, lv_pct(66));
lv_obj_set_height( ui_URLLabel, lv_pct(10));
lv_obj_set_x( ui_URLLabel, 51 );
lv_obj_set_y( ui_URLLabel, 68 );
lv_obj_set_align( ui_URLLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_URLLabel,"");
lv_obj_set_style_text_font(ui_URLLabel, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);


}
