// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: amoled_display

#include "ui.h"

void ui_welcomeScreen_screen_init(void)
{
ui_welcomeScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_welcomeScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_welcomeLabel = lv_label_create(ui_welcomeScreen);
lv_obj_set_width( ui_welcomeLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_welcomeLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_welcomeLabel, 0 );
lv_obj_set_y( ui_welcomeLabel, -12 );
lv_obj_set_align( ui_welcomeLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_welcomeLabel,"Weclcome to Shottimer\n\n						Starting ....");
lv_obj_set_style_text_font(ui_welcomeLabel, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);


}
